create table PUBLIC.CUSTOMER (
	ID           INTEGER auto_increment primary key,
	BIRTH_DATE   DATE,
	EMAIL        CHARACTER VARYING(255),
	FIRST_NAME   CHARACTER VARYING(255),
	LAST_NAME    CHARACTER VARYING(255),
	MIDDLE_NAME  CHARACTER VARYING(255),
	PHONE_NUMBER CHARACTER VARYING(255)
);

create table PUBLIC.QUOTATION (
	ID                       INTEGER auto_increment primary key,
	BEGINING_OF_INSURANCE    TIMESTAMP WITH TIME ZONE,
	DATE_OF_SIGNING_MORTGAGE TIMESTAMP WITH TIME ZONE,
	INSURED_AMOUNT           NUMERIC(38, 2),
	CUSTOMER_ID              INTEGER,
	constraint FKLF5TI8FW77UEW5IVT1RH1DLRD
		foreign key (CUSTOMER_ID) references PUBLIC.CUSTOMER
);

create table PUBLIC.SUBSCRIPTION (
	ID           INTEGER auto_increment primary key,
	START_DATE   TIMESTAMP WITH TIME ZONE,
	VALID_UNTIL  TIMESTAMP WITH TIME ZONE,
	QUOTATION_ID INTEGER,
	constraint FKIHOXJLVO15JU9Q666B54BENN3
		foreign key (QUOTATION_ID) references PUBLIC.QUOTATION
);

